### ISSUE TITLE
Rest API for detector

### ISSUE THREAD

**Issue by adrabi-abderrahim** [FightCOVID19/core#1]
Creating a Rest API, to let anyone to consume it freely. Of course, we can also consume it in web/application applications.

I think many people prefer to use desktop applications with local storages, using the Rest API can give to them an opportunity to do computation/detection online to reduce _local_ computations.

**Comment by elcronos** [comment]
@adrabi-abderrahim I am not sure if you are up-to-date with our research. Instead of detecting coronavirus we will be detecting suspicions vs non-suspicious xrays. Some of the reasons for doing that is that the quality of the public datasets are not good enough for creating a reliable COVID-19 classifier. So having that into account I still think it is a good idea to create an API. However. that also means we will need to run with the costs and unfortunately at the moment it is not feasible. We might consider this option once we get some sponsors or more credits from the Cloud providers.

![image](https://user-images.githubusercontent.com/9023043/77695855-63c1df80-6fe7-11ea-8888-938d8d223c1b.png)
